// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB',
        defaultValue: 'AIza' 'SyB73ovBXEht49nlvCfO4zSSJlPHrSvQROY'),
    appId: '1:842933413489:web:e156d51865070a60fc1dd0',
    messagingSenderId: '842933413489',
    projectId: 'meal-manager-844f5',
    authDomain: 'meal-manager-844f5.firebaseapp.com',
    storageBucket: 'meal-manager-844f5.firebasestorage.app',
    measurementId: 'G-0VWS848J2R',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_ANDROID',
        defaultValue: 'AIza' 'SyDcLgrt4AZW2BYlvOvXc5d1GZbvATKYSDk'),
    appId: '1:842933413489:android:65e90921f4879675fc1dd0',
    messagingSenderId: '842933413489',
    projectId: 'meal-manager-844f5',
    storageBucket: 'meal-manager-844f5.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS',
        defaultValue: 'AIza' 'SyBtwX20ZsFfRdEZUQwuYf-VlW7PRobg9Iw'),
    appId: '1:842933413489:ios:26c1329003386999fc1dd0',
    messagingSenderId: '842933413489',
    projectId: 'meal-manager-844f5',
    storageBucket: 'meal-manager-844f5.firebasestorage.app',
    iosClientId: '842933413489-lgbv73mm0309l1fov703gvk6lvfs5ufl.apps.googleusercontent.com',
    iosBundleId: 'com.example.messManager',
  );
}
